// ==========================================
// FILE: src/controllers/geminiNegotiationController.ts
// ==========================================

import { GoogleGenAI, Type, Schema } from '@google/genai';

// Initialize SDK using the current standard constructor syntax
const ai = new GoogleGenAI();

export interface NegotiationContext {
  sessionId: string;
  productName: string;
  listPrice: number;
  floorPrice: number;
  aiPersona: 'AGGRESSIVE' | 'BALANCED' | 'FRIENDLY' | 'FIRM';
  maxRounds: number;
  currentRound: number;
  buyerOffer: number;
  conversationHistory?: Array<{
    sender: 'BUYER' | 'AI_AGENT' | 'HUMAN_SELLER';
    amount?: number;
    message?: string;
  }>;
}

export interface NegotiationDecision {
  action: 'COUNTER' | 'ACCEPT' | 'REJECT';
  counterAmount: number;
  reasoning: string;
  buyerMessage: string;
}

// Structured Output Schema Enforcement
const responseSchema: Schema = {
  type: Type.OBJECT,
  properties: {
    action: {
      type: Type.STRING,
      enum: ['COUNTER', 'ACCEPT', 'REJECT'],
      description: 'The strategy decision: COUNTER to negotiate, ACCEPT if offer meets criteria, REJECT if too far below floor.',
    },
    counterAmount: {
      type: Type.NUMBER,
      description: 'The numeric counter-offer amount generated by AI. Set to current offer if accepted/rejected.',
    },
    reasoning: {
      type: Type.STRING,
      description: 'Internal analytical summary explaining why this strategic decision and counter-offer were chosen.',
    },
    buyerMessage: {
      type: Type.STRING,
      description: 'The customer-facing text response sent directly to the buyer explaining the offer.',
    },
  },
  required: ['action', 'counterAmount', 'reasoning', 'buyerMessage'],
};

/**
 * Computes an autonomous negotiation counter-offer using Gemini 2.5 Flash
 */
export async function computeNegotiationDecision(
  context: NegotiationContext
): Promise<NegotiationDecision> {
  const systemInstruction = `
You are an autonomous e-commerce negotiation AI agent acting on behalf of the seller.
Your objective is to maximize profit margin while successfully closing deals within the seller's guardrails.

CRITICAL GUARDRAILS:
1. NEVER offer a price below the floor price ($${context.floorPrice}).
2. List Price is $${context.listPrice}.
3. Maximum rounds allowed: ${context.maxRounds}. Current round: ${context.currentRound}.
4. Configured AI Persona: ${context.aiPersona}.
   - AGGRESSIVE: Protect margin fiercely. Make minimal price drops.
   - BALANCED: Concede steadily to reach a fair middle ground.
   - FRIENDLY: High empathy, prioritize fast sales with moderate concessions.
   - FIRM: Hold near list price, emphasize quality and value over discounts.

RULES:
- If buyer's offer is >= List Price or >= Floor Price on the final round, prefer ACCEPT.
- If buyer's offer is below Floor Price, make a COUNTER at or above Floor Price, or REJECT if far too low on late rounds.
- Never output markdown in the buyerMessage or reasoning fields. Return plain text only.
`;

  const prompt = `
Negotiation Context:
- Item: ${context.productName}
- List Price: $${context.listPrice}
- Floor Price: $${context.floorPrice}
- Buyer's Latest Offer: $${context.buyerOffer}
- Current Round: ${context.currentRound} of ${context.maxRounds}
- History: ${JSON.stringify(context.conversationHistory || [])}

Evaluate this offer and decide whether to COUNTER, ACCEPT, or REJECT. Provide a exact numeric counter amount and customer message.
`;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
      config: {
        systemInstruction,
        responseMimeType: 'application/json',
        responseSchema,
        temperature: 0.2, // Low temperature for consistent financial logic
      },
    });

    const resultText = response.text;
    if (!resultText) {
      throw new Error('Empty response received from Gemini API');
    }

    const decision: NegotiationDecision = JSON.parse(resultText);

    // Fallback Safety Verification
    if (decision.counterAmount < context.floorPrice && decision.action === 'COUNTER') {
      console.warn(`[Gemini AI Guardrail Triggered] AI suggested $${decision.counterAmount} below floor $${context.floorPrice}. Clamping to floor.`);
      decision.counterAmount = context.floorPrice;
    }

    return decision;
  } catch (error) {
    console.error('[Gemini AI Controller Error]:', error);

    // Fallback programmatic calculation if API fails
    const defaultCounter = Math.max(
      context.floorPrice,
      Math.round(context.listPrice - (context.listPrice - context.buyerOffer) * 0.5)
    );

    return {
      action: context.buyerOffer >= context.floorPrice ? 'ACCEPT' : 'COUNTER',
      counterAmount: defaultCounter,
      reasoning: 'Fallback negotiation rule applied due to controller exception.',
      buyerMessage: `Thank you for your offer of $${context.buyerOffer}. I can meet you at $${defaultCounter}.`,
    };
  }
}
