// ==========================================
// FILE: backend/src/controllers/geminiNegotiationController.ts
// ==========================================

import { GoogleGenAI, Type, Schema } from '@google/genai';

// Initialize SDK using the explicit API key from environment variables (supporting both naming conventions) to prevent initialization failure
const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || process.env.API_KEY });

export interface NegotiationContext {
  sessionId: string;
  productName: string;
  listPrice: number;
  floorPrice: number;
  aiPersona: 'AGGRESSIVE' | 'BALANCED' | 'FRIENDLY' | 'FIRM';
  maxRounds: number;
  currentRound: number;
  buyerOffer: number;
  conversationHistory?: Array<{
    sender: 'BUYER' | 'AI_AGENT' | 'HUMAN_SELLER';
    amount?: number;
    message?: string;
  }>;
}

export interface NegotiationDecision {
  action: 'COUNTER' | 'ACCEPT' | 'REJECT';
  counterAmount: number;
  reasoning: string;
  buyerMessage: string;
}

// Structured Output Schema Enforcement
const responseSchema: Schema = {
  type: Type.OBJECT,
  properties: {
    action: {
      type: Type.STRING,
      enum: ['COUNTER', 'ACCEPT', 'REJECT'],
      description: 'The strategy decision: COUNTER to negotiate, ACCEPT if offer meets criteria, REJECT if too far below floor.',
    },
    counterAmount: {
      type: Type.NUMBER,
      description: 'The numeric counter-offer amount generated by AI. Set to current offer if accepted/rejected.',
    },
    reasoning: {
      type: Type.STRING,
      description: 'Internal analytical summary explaining why this strategic decision and counter-offer were chosen.',
    },
    buyerMessage: {
      type: Type.STRING,
      description: 'The customer-facing text response sent directly to the buyer explaining the offer.',
    },
  },
  required: ['action', 'counterAmount', 'reasoning', 'buyerMessage'],
};

/**
 * Computes an autonomous negotiation counter-offer using Gemini 3.6 Flash with fallback support for 2.5 Flash
 */
export async function computeNegotiationDecision(
  context: NegotiationContext
): Promise<NegotiationDecision> {
  const lastMsg = context.conversationHistory?.[context.conversationHistory.length - 1]?.message || '';
  const isGeneralQuery = /^(2\s*\+\s*2|hello|hi|hey|code|python|javascript|typescript|function|how\s+are\s+you|what\s+is\s+your\s+name|help|write\s+a\s+code|can\s+you\s+do\s+it)\b/i.test(lastMsg.trim());

  // Helper function to try generating content with fallback models starting with the updated model first
  async function generateWithModelFallback(params: {
    contents: any;
    config?: any;
  }) {
    const modelsToTry = ['gemini-3.6-flash', 'gemini-2.5-flash'];
    let lastError: any;

    for (const modelName of modelsToTry) {
      try {
        const response = await ai.models.generateContent({
          model: modelName,
          contents: params.contents,
          config: params.config,
        });
        return response;
      } catch (err: any) {
        console.warn(`[Gemini Model Warning] Model ${modelName} failed:`, err.message || err);
        lastError = err;
      }
    }
    throw lastError;
  }

  // If it's a general query, use generateWithModelFallback
  if (isGeneralQuery) {
    try {
      const systemInstruction = `You are TRADARA AI, an advanced, highly intelligent AI assistant built for TRADARA.
You are fully equipped to answer general knowledge questions, solve math problems (such as evaluating 2+2 or equations), write and debug code, explain complex technical concepts, and assist users directly with absolute precision.
Provide precise, direct, and insightful answers without forcing e-commerce or price negotiation prompts.`;

      const response = await generateWithModelFallback({
        contents: `User says: "${lastMsg}"`,
        config: {
          systemInstruction,
          temperature: 0.3,
        },
      });

      const textReply = response.text || `Hello! How can I help you today?`;

      return {
        action: 'COUNTER',
        counterAmount: context.buyerOffer,
        reasoning: 'General assistant query answered directly.',
        buyerMessage: textReply,
      };
    } catch (error: any) {
      console.error('[TRADARA AI CRITICAL FAILURE]:', {
        message: error.message,
        status: error.status,
        stack: error.stack,
      });
      throw new Error(`AI Provider Failed: ${error.message || 'Unknown configuration error'}`);
    }
  }

  const systemInstruction = `
You are TRADARA AI, an autonomous e-commerce negotiation AI agent acting on behalf of the seller.
Your objective is to maximize profit margin while successfully closing deals within the seller's guardrails.
You are fully equipped to handle general inquiries, coding problems, mathematics, and expert negotiations across any field or domain.

CRITICAL GUARDRAILS:
1. NEVER offer a price below the floor price ($${context.floorPrice}).
2. List Price is $${context.listPrice}.
3. Maximum rounds allowed: ${context.maxRounds}. Current round: ${context.currentRound}.
4. Configured AI Persona: ${context.aiPersona}.
   - AGGRESSIVE: Protect margin fiercely. Make minimal price drops.
   - BALANCED: Concede steadily to reach a fair middle ground.
   - FRIENDLY: High empathy, prioritize fast sales with moderate concessions.
   - FIRM: Hold near list price, emphasize quality and value over discounts.

RULES:
- If buyer's offer is >= List Price or >= Floor Price on the final round, prefer ACCEPT.
- If buyer's offer is below Floor Price, make a COUNTER at or above Floor Price, or REJECT if far too low on late rounds.
- Never output markdown in the buyerMessage or reasoning fields. Return plain text only.
`;

  const prompt = `
Negotiation Context:
- Item: ${context.productName}
- List Price: $${context.listPrice}
- Floor Price: $${context.floorPrice}
- Buyer's Latest Offer: $${context.buyerOffer}
- Current Round: ${context.currentRound} of ${context.maxRounds}
- History: ${JSON.stringify(context.conversationHistory || [])}

Evaluate this offer and decide whether to COUNTER, ACCEPT, or REJECT. Provide an exact numeric counter amount and customer message.
`;

  try {
    const response = await generateWithModelFallback({
      contents: prompt,
      config: {
        systemInstruction,
        responseMimeType: 'application/json',
        responseSchema,
        temperature: 0.2, // Low temperature for consistent financial logic
      },
    });

    const resultText = response.text;
    if (!resultText) {
      throw new Error('Empty response received from Gemini API');
    }

    const decision: NegotiationDecision = JSON.parse(resultText);

    // Fallback Safety Verification
    if (decision.counterAmount < context.floorPrice && decision.action === 'COUNTER') {
      console.warn(`[Gemini AI Guardrail Triggered] AI suggested $${decision.counterAmount} below floor $${context.floorPrice}. Clamping to floor.`);
      decision.counterAmount = context.floorPrice;
    }

    return decision;
  } catch (error: any) {
    console.error('[TRADARA AI CRITICAL FAILURE]:', {
      message: error.message,
      status: error.status,
      stack: error.stack,
    });
    throw new Error(`AI Provider Failed: ${error.message || 'Unknown configuration error'}`);
  }
}